# docker-compose.frontend.yaml

services:
  traefik:
    image: traefik:v3.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--ping=true"
      - "--ping.entrypoint=traefik"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:3100"
      # Allow ACME challenge before redirect
      - "--entrypoints.web.http.middlewares=redirect-to-https@file"
      # Certificate Resolver configuration
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "3100:3100" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - "./traefik:/etc/traefik"
    networks:
      - frontend_net
    environment:
      - "ACME_EMAIL=${ACME_EMAIL}"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - frontend_net
    volumes:
      - redis_data:/data
    restart: unless-stopped

  auction-manager:
    build:
      context: ./apps/auction-manager
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=4100
      - METRICS_PORT=4190
      - HEALTH_PORT=4191
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/auction-manager:/app
      - /app/node_modules
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auction-manager.rule=Host(`${AUCTION_MANAGER_SUBDOMAIN}`)"
      - "traefik.http.services.auction-manager.loadbalancer.server.port=4100"
      - "traefik.http.routers.auction-manager.entrypoints=websecure"
      - "traefik.http.routers.auction-manager.tls.certresolver=letsencrypt"
    ports:
      - "4100:4100" # Main API
      - "4190:4190" # Metrics
      - "4191:4191" # Health
    depends_on:
      - redis
    command: npm run dev

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    networks:
      - frontend_net
    depends_on:
      - redis
    command: --redis.addr=redis://redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-metrics.rule=Host(`${MONITORING_SUBDOMAIN}`) && PathPrefix(`/redis-metrics`)"
      - "traefik.http.services.redis-metrics.loadbalancer.server.port=9121"
      - "traefik.http.routers.redis-metrics.entrypoints=websecure"
      - "traefik.http.routers.redis-metrics.tls.certresolver=letsencrypt"
      - "traefik.http.routers.redis-metrics.middlewares=redis-metrics-strip"
      - "traefik.http.middlewares.redis-metrics-strip.stripprefix.prefixes=/redis-metrics"

  prometheus:
    image: prom/prometheus:v2.48.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=https://${MONITORING_SUBDOMAIN}/prometheus"
      - "--web.route-prefix=/prometheus"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`${MONITORING_SUBDOMAIN}`) && PathPrefix(`/prometheus`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SERVER_ROOT_URL=https://${MONITORING_SUBDOMAIN}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/system-metrics.json
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${MONITORING_SUBDOMAIN}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
    depends_on:
      - prometheus

  admin-frontend:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - DOCKER_SOCKET=/var/run/docker.sock
      - WATCHPACK_POLLING=true
      - PORT=3000
      - METRICS_PORT=3090
      - HEALTH_PORT=3091
      - NEXT_PUBLIC_EVENT_HANDLER_SUBDOMAIN=${EVENT_HANDLER_SUBDOMAIN}
      - PROMETHEUS_URL=http://prometheus:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Development volumes - modified for better compatibility
      - ./apps/admin:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`${ADMIN_SUBDOMAIN}`)"
      - "traefik.http.services.admin.loadbalancer.server.port=3000"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
    command: npm run dev
    ports:
      - "3000:3000" # Main App
      - "3090:3090" # Metrics
      - "3091:3091" # Health

  event-handler:
    build:
      context: ./apps/event-handler
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=4300
      - EVENT_STREAM_PORT=4301
      - METRICS_PORT=4390
      - HEALTH_PORT=4391
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./apps/event-handler:/app
      - /app/node_modules
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event-handler.rule=Host(`${EVENT_HANDLER_SUBDOMAIN}`)"
      - "traefik.http.services.event-handler.loadbalancer.server.port=4300"
      - "traefik.http.routers.event-handler.entrypoints=websecure"
      - "traefik.http.routers.event-handler.tls.certresolver=letsencrypt"
      # Event stream endpoint
      - "traefik.http.routers.event-stream.rule=Host(`${EVENT_HANDLER_SUBDOMAIN}`) && PathPrefix(`/events`)"
      - "traefik.http.services.event-stream.loadbalancer.server.port=4301"
      - "traefik.http.routers.event-stream.entrypoints=websecure"
      - "traefik.http.routers.event-stream.tls.certresolver=letsencrypt"
    ports:
      - "4300:4300" # Main API
      - "4301:4301" # Event Stream
      - "4390:4390" # Metrics
      - "4391:4391" # Health
    depends_on:
      - redis

volumes:
  letsencrypt:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  frontend_net:
    driver: bridge 