FROM node:22-slim

# Install pnpm and dependencies
RUN npm install -g pnpm@9.15.1 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    python3 \
    make \
    g++ \
    cmake \
    # Dependencies for canvas
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev \
    # Clean up
    && rm -rf /var/lib/apt/lists/*

# Switch to node user early
USER node
WORKDIR /app

# Create directory structure
RUN mkdir -p /app/storage/db \
            /app/storage/data \
            /app/storage/characters

# Copy package files
COPY --chown=node:node package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy source files
COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node ./src ./src

EXPOSE 3000

# Run in development mode with hot reloading
CMD ["pnpm", "dev"] 