version: '3.8'

services:
  auction-manager:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "4100:4100"

  event-handler:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "4300:4300"

  stream-manager:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "4200:4200"

  shape-l2:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
    ports:
      - "4000:4000"

  eliza:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G
    ports:
      - "4400:4400"

  admin-frontend:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "3000:3000"

  redis:
    restart: unless-stopped
    command: redis-server --protected-mode no --maxmemory 2gb --maxmemory-policy allkeys-lru
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - "6379:6379"

  prometheus:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    ports:
      - "9090:9090"

  grafana:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "3001:3000"

  # Production-only services
  nginx:
    profiles: []  # Enables the service in production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
      - prometheus
      - admin-frontend
    networks:
      - auction_net

  backup:
    image: alpine
    volumes:
      - ./storage:/backup/storage:ro
      - ./scripts/backup.sh:/backup.sh:ro
    command: sh -c "crond -f"
    restart: unless-stopped 