version: '3.8'

services:
  auction-manager:
    build:
      context: ./apps/auction-manager
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/auction-manager/src:/app/src:ro
      - ./apps/auction-manager/package.json:/app/package.json:ro
      - ./storage/auction:/app/storage:rw
    command: npm run dev

  event-handler:
    build:
      context: ./apps/event-handler
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/event-handler/src:/app/src:ro
      - ./apps/event-handler/package.json:/app/package.json:ro
    command: npm run dev

  stream-manager:
    build:
      context: ./apps/stream-manager
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/stream-manager/src:/app/src:ro
      - ./apps/stream-manager/package.json:/app/package.json:ro
      - ./storage/stream:/app/storage:rw
    command: npm run dev

  shape-l2:
    build:
      context: ./apps/shape-l2
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - USE_MOCK_BLOCKCHAIN=true
    volumes:
      - ./apps/shape-l2/src:/app/src:ro
      - ./apps/shape-l2/package.json:/app/package.json:ro
      - ./storage/shape-l2:/app/storage:rw
    command: npm run dev

  eliza:
    build:
      context: ./apps/eliza
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - USE_MOCK_APIS=true
    volumes:
      - ./apps/eliza/src:/app/src:ro
      - ./apps/eliza/package.json:/app/package.json:ro
      - ./apps/eliza/tsconfig.json:/app/tsconfig.json:ro
      - ./apps/eliza/pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./storage/eliza/characters:/app/storage/characters:rw
      - ./storage/eliza/db:/app/storage/db:rw
      - ./storage/eliza/data:/app/storage/data:rw
      - ./storage/eliza/cache:/app/storage/cache:rw
    command: npm run dev

networks:
  auction_net:
    driver: bridge 