http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        port: "443"

  routers:
    # ACME challenge router - must be first to handle challenges
    acme-http:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop@internal
      priority: 100

    # General HTTP to HTTPS redirect
    http-catchall:
      rule: "HostRegexp(`{host:.+}`) && !PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal
      priority: 1

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      alpnProtocols:
        - h2
        - http/1.1
        - acme-tls/1