global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'admin-frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['admin-frontend:3090']

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis:6379'] 