global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Common configuration for all services
  - job_name: 'common'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 'traefik:3100'          # Traefik's own metrics
        - 'admin-frontend:3090'    # Admin frontend metrics
        - 'event-handler:4390'     # Event handler metrics
        - 'stream-manager:4290'     # Stream manager metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(up|process_cpu_seconds_total|process_resident_memory_bytes|http_request_duration_seconds_count)$'
        action: keep

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(up|process_cpu_seconds_total|process_resident_memory_bytes)$'
        action: keep

  # Redis specific configuration (uses redis-exporter)
  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-exporter:9121']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(redis_up|redis_memory_used_bytes|redis_connected_clients|redis_commands_processed_total)$'
        action: keep 