name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [admin, stream-manager, auction-engine, event-handler]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          push: false
          load: true
          tags: sothebais-${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_MODE=production
      
      # Uncomment and adapt when tests are configured
      # - name: Run tests in Docker container
      #   run: |
      #     docker run --rm sothebais-${{ matrix.service }}:test npm test